### ISSUE TITLE
FP issue - tokens not getting a %

### ISSUE THREAD

**Issue by Ivan1905** [sprtd/rake-scam-token-forta-detection-bot#1]
Hey there,

I found a few alerts that in my opinion wrongly flagged a a few addresses as deployers of rake token contract.

e.g1: https://explorer.forta.network/alert/0x9c79643c8a7fd2042fe194ca7270bebf596ed88df4714d5576ce0fd40afdf697
This address deployed a token called IS but on the swaps I'm looking over, I cannot find any address extracting any commission.

E.g2: https://explorer.forta.network/alert/0x68e35980785bbe99cae3b2edac36e549ee65c7c968e393736ad0c430a9da521d
Same here with this token called CAMO.

**Comment by sprtd** [comment]
sure, I will take a look and revert back

**Comment by sprtd** [comment]
> Hey there,
> 
> I found a few alerts that in my opinion wrongly flagged a a few addresses as deployers of rake token contract.
> 
> e.g1: https://explorer.forta.network/alert/0x9c79643c8a7fd2042fe194ca7270bebf596ed88df4714d5576ce0fd40afdf697 This address deployed a token called IS but on the swaps I'm looking over, I cannot find any address extracting any commission.
> 
> E.g2: https://explorer.forta.network/alert/0x68e35980785bbe99cae3b2edac36e549ee65c7c968e393736ad0c430a9da521d Same here with this token called CAMO.

@Ivan1905 I have fixed and published the updated version; please, refer to the [fix](https://github.com/sprtd/rake-scam-token-forta-detection-bot/pull/2)
Feel free to reach out if you have any question regarding this error
